### ISSUE TITLE
openapi  from odata error

### ISSUE THREAD

**Issue by marcioatws** [microsoft/kiota-typescript#1329]
I generated the openapi spec from an odata application and the typescript client in kiota didn't work with the url parentheses. for example, for the url http://aaaa.bbb/entities({id}) in the model, a method called entitiesWithId(type | undefined) was generated and when used it causes an error that entitiesWithId is not a function. i can generate some code for error reproduction if need it. 

Another situation is that using the "strict" option in the typescript settings, the following error message is generated in all models:

src/app/models/contratoAggregate/index.ts:125:95 - error TS2345: Argument of type '(writer: SerializationWriter, contrato?: Partial<Contrato> | undefined) => void' is not assignable to parameter of type 'ModelSerializerFunction<Contrato>'.
  Types of parameters 'contrato' and 'value' are incompatible.
    Type 'Partial<Contrato> | null | undefined' is not assignable to type 'Partial<Contrato> | undefined'.
      Type 'null' is not assignable to type 'Partial<Contrato> | undefined'.

    writer.writeCollectionOfObjectValues<Contrato>("value", contratoCollectionResponse.value, serializeContrato);

**Comment by baywet** [comment]
Hi @marcioatws 
Thank you for using kiota and for reaching out.

For the parameter type this was introduced by #1248 and needs the corresponding generator changes to function properly https://github.com/microsoft/kiota/pull/5163. You can use [the latest preview release](https://github.com/microsoft/kiota/releases/tag/v1.18.0-preview.202408150001) and re-generate the client.

For the non-existent function, can you provide a repro description please?
